name: n47_web
description: N47° ExtremeSport League e.V.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI / Fonts / Icons
  cupertino_icons: ^1.0.9
  google_fonts: ^6.3.3
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12

  # State Management & Utilities
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.2
  intl: ^0.20.0
  logger: ^2.8.0

  # Local Storage
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  shared_preferences: ^2.5.5
  shared_preferences_web: ^2.4.3

  # Firebase Core & Products
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_app_check: ^0.3.1+9

  # Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation Tools
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  hive_ce_generator: ^1.11.3
  flutter_gen: ^5.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/future/mobile/
    - assets/images/future/web/
    - assets/images/history/mobile/
    - assets/images/history/web/
    - assets/icons/
    - assets/data/
    - assets/qr/
    - assets/supporters/

  generate: true

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 700