// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcKexkEZGY3JVN8XNA2Rpmfph3h1qp4SM',
    appId: '1:187191289365:web:8ee318c2535140d179d01c',
    messagingSenderId: '187191289365',
    projectId: 'n47web',
    authDomain: 'n47web.firebaseapp.com',
    storageBucket: 'n47web.firebasestorage.app',
    measurementId: 'G-28YXXJ4R3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1qEJ-JeIKNRqEgMflm4valbdTinnJUQA',
    appId: '1:187191289365:android:865269b3fdaa18c779d01c',
    messagingSenderId: '187191289365',
    projectId: 'n47web',
    storageBucket: 'n47web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJ9mvLiUDxYhGlMxa3crLSJBxJ_mMIBs',
    appId: '1:187191289365:ios:65d82b15f266a10879d01c',
    messagingSenderId: '187191289365',
    projectId: 'n47web',
    storageBucket: 'n47web.firebasestorage.app',
    iosBundleId: 'eu.n47.n47Web',
  );

}