// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:n47_web/database/event.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EventHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(EventHiveAdapter());
  }
}
