name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # 使用稳定版
          flutter-version: '3.29.2'  # 指定你的Flutter版本
      
      # 缓存依赖
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build/web
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
      
      # 安装依赖
      - name: Install dependencies
        run: flutter pub get
      
      # 构建项目
      - name: Build Flutter Web
        run: flutter build web --release
      
      # 部署到Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_N47WEB }}
          channelId: live
          projectId: n47web