name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.16.0'  # 使用你项目实际的Flutter版本

      # 缓存依赖
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build/web
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}

      # 安装依赖
      - name: Install dependencies
        run: |
          flutter pub get
          npm install  # 如果同时使用npm依赖

      # 构建项目
      - name: Build Flutter Web
        run: flutter build web --release

      # 部署预览环境
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_N47WEB }}
          projectId: n47web
          expires: 7d  # 预览链接7天后过期
          message: "PR Preview: ${{ github.event.pull_request.title }}"